"""模块间 Protocol 接口（冻结契约）。

每个接口对应 registry.ROLE 的一个角色。模块实现自己那个接口并注册；消费方按接口编码。
用 typing.Protocol（结构化子类型）：实现者无需继承、无需 import 本文件即可满足，进一步解耦。

**并行开发约定**：这些接口签名是冻结的。要改接口须先在此提出并更新 docs/CONTRACTS.md，
通知所有并行方——不可某个 AI 单方面改接口破坏别人。
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class IntelService(Protocol):
    """情报中心：扫描后归集资产、按 task 查资产/系统。intel 模块实现。"""
    def collect_from_task(self, task_id: str) -> Dict[str, Any]: ...
    def auto_collect_after_scan(self, task_id: str) -> Dict[str, Any]: ...


@runtime_checkable
class FindingService(Protocol):
    """漏洞发现：登记/查询/统计 intel_finding。finding 归 intel 模块。"""
    def record_finding(self, finding: Dict[str, Any]) -> Any: ...
    def is_identify_poc(self, plg_name: str, vul_name: str) -> bool: ...


@runtime_checkable
class PentestDispatcher(Protocol):
    """AI 渗透派发：按资产建会话、批量派发。ai_pentest 模块实现。"""
    def batch_create_from_assets(self, asset_keys: Optional[List[str]] = None,
                                 **kwargs: Any) -> Any: ...
    def run_session(self, session_id: str) -> Any: ...


@runtime_checkable
class VulnIntelService(Protocol):
    """漏洞情报查询：按组件/关键词查。vuln 模块实现。"""
    def query(self, keyword: str, **kwargs: Any) -> List[Dict[str, Any]]: ...


@runtime_checkable
class ReconService(Protocol):
    """侦察服务：调 sentinel_engine 完成侦察能力（JS挖掘/nuclei/dns/PoC/弱口令等）。recon_bridge 实现。

    方法标准见 docs/CONTRACTS.md §二 RECON。查询类返回 list[dict]（无则 []），run_recon 返回结果摘要 dict。
    """
    def run_recon(self, task_type: str, task_id: str, target: Any,
                  **kwargs: Any) -> Dict[str, Any]: ...
    def collect_js(self, site: str, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def nuclei_scan(self, targets: List[str], **kwargs: Any) -> List[Dict[str, Any]]: ...
    def run_poc(self, plugins: List[str], targets: List[str], **kwargs: Any) -> List[Dict[str, Any]]: ...
    def weak_brute(self, host: str, port: int, scheme: str, **kwargs: Any) -> List[Dict[str, Any]]: ...
    def dns_query(self, domain: str, **kwargs: Any) -> List[Dict[str, Any]]: ...


@runtime_checkable
class ProxyService(Protocol):
    """出口代理：决策代理 URL / 健康检查。proxy 模块实现。"""
    def resolve_egress(self, prefer: str, source: str = "") -> Any: ...
    def check_health(self, **kwargs: Any) -> bool: ...


@runtime_checkable
class NotifyService(Protocol):
    """通知推送：飞书/钉钉/企业微信/邮件。integration 模块实现。"""
    def notify(self, message: str, **kwargs: Any) -> Any: ...


@runtime_checkable
class ExploitClueService(Protocol):
    """共享情报池：单位级凭证/线索读写。intel 模块实现。"""
    def write_clue(self, clue: Dict[str, Any]) -> Any: ...
    def query_clues(self, scope: Dict[str, Any]) -> List[Dict[str, Any]]: ...


@runtime_checkable
class SystemTagsService(Protocol):
    """系统命名/标签：给资产取系统名、抽标签。intel 模块实现。"""
    def pick_system_name(self, asset: Dict[str, Any]) -> str: ...
    def extract_tags(self, data: Dict[str, Any]) -> List[str]: ...


@runtime_checkable
class UserService(Protocol):
    """登录鉴权 / token 校验 / 用户 CRUD。system/user_manage 实现，router 网关消费。"""
    def login(self, username: str, password: str) -> Dict[str, Any]: ...
    def verify_token(self, token: str) -> Optional[Dict[str, Any]]: ...
    def change_password(self, username: str, old_pw: str, new_pw: str) -> Dict[str, Any]: ...
    def list_users(self) -> List[Dict[str, Any]]: ...
    def create_user(self, username: str, password: str, role: str, **kwargs: Any) -> Dict[str, Any]: ...
    def update_user(self, username: str, **kwargs: Any) -> Dict[str, Any]: ...
    def delete_user(self, username: str, **kwargs: Any) -> Dict[str, Any]: ...


@runtime_checkable
class RbacService(Protocol):
    """权限校验 / 角色管理。system/user_manage 实现，router 网关消费（check_permission 是网关核心）。"""
    def check_permission(self, user: Dict[str, Any], path: str, method: str) -> Any: ...
    def resolve_perms(self, user: Dict[str, Any]) -> List[str]: ...
    def list_roles(self) -> List[Dict[str, Any]]: ...
    def upsert_role(self, name: str, permissions: List[str], **kwargs: Any) -> Dict[str, Any]: ...
    def delete_role(self, name: str) -> Dict[str, Any]: ...
    def list_permissions(self) -> List[Dict[str, Any]]: ...
